[package]
name = "json-encoder-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]
# wasm-pack has some problems with workspaces.

[dependencies]
# https://github.com/rust-random/getrandom/issues/208
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
json-oracle-encoder = { path = "../../crates/json-oracle-encoder" }
serde_json = "1"
wasm-bindgen = "0.2.88"
